# Generated by Django 4.2.6 on 2023-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('hability', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hability')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('api_creation', models.BooleanField(blank=True, null=True, verbose_name='Api Creation')),
            ],
        ),
    ]
