# Generated by Django 4.2.6 on 2023-10-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='hability',
        ),
        migrations.CreateModel(
            name='PokemonHability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hability', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokemon.pokemon', verbose_name='Name')),
            ],
        ),
    ]
