# Generated by Django 4.2.6 on 2023-10-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0003_hability_delete_pokemonhability_pokemon_hability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hability',
            new_name='Ability',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='hability',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability',
            field=models.ManyToManyField(blank=True, to='Pokemon.ability', verbose_name='Abilities'),
        ),
    ]
